### ISSUE TITLE
从源码编译安装失败, SharedSupport 目录下缺少相应的文件

### ISSUE THREAD

**Issue by jk2K** [rime/squirrel#104]
``` bash
ls /Library/Input\ Methods/Squirrel.app/Contents/SharedSupport
installation.yaml squirrel.yaml
```

由于`SharedSupport`目录下缺少相应的文件, 导致编译的时候, 报`Error loading config from './default.yaml'`错误

``` bash
sudo make install
Password:
rm -rf "/Library/Input Methods/Squirrel.app"
cp -R build/Release/Squirrel.app "/Library/Input Methods"
"/Library/Input Methods/Squirrel.app/Contents/Resources/postflight"
RIME_SHARED_DATA_PATH=/Library/Input Methods/Squirrel.app/Contents/SharedSupport
precompiling Rime schemata. patience...
E0601 13:16:41.792810 2082832384 customizer.cc:56] Error loading config from './default.yaml'.
E0601 13:16:41.793009 2082832384 customizer.cc:56] Error loading config from './symbols.yaml'.
E0601 13:16:41.793037 2082832384 deployment_tasks.cc:129] Error loading default config from './default.yaml'.
2016-06-01 13:16:41.820 Squirrel[4951:78175] RegisterInputSource.
2016-06-01 13:16:41.868 Squirrel[4951:78175] DeactivateInputSource
```

步骤是按照 [INSTALL.md](https://github.com/rime/squirrel/blob/develop/INSTALL.md) 一步步来的

**Comment by lotem** [comment]
抱歉，計劃改爲程序和數據文件分開發佈，現在做到一半。
可以忽略這個錯誤，把[所需 YAML 文件](https://github.com/rime/brise)手動下載到 `$HOME/Library/Rime/` 即可。

**Comment by jk2K** [comment]
我复制了所需的`YAML`文件，然后遇到了无法切换配置的问题

具体来说就是，一直都是繁体输入，无法切换为简体
![image](https://cloud.githubusercontent.com/assets/4025839/15736350/c926e37c-28d1-11e6-9cf2-cb7404015f7a.png)

**Comment by lotem** [comment]
還少一樣，編譯完成後，把 `data/opencc` 這個目錄也複製到 `$HOME/Library/Rime/`。

**Comment by jk2K** [comment]
完美，正常工作了，非常感谢

**Comment by jk2K** [comment]
发现`default.custom.yaml`不生效, 
这是我的`default.custom.yaml`文件内容
```yaml
# default.custom.yaml
patch:
  schema_list:
      - schema: double_pinyin_flypy
      - schema: luna_pinyin
      - schema: luna_pinyin_simp
      - schema: luna_pinyin_tw

  menu/page_size: 9
```

**Comment by gshmu** [comment]
我不是自己编译的，也有这个问题。 从前不久升级后就一直有问题……
Process:               Squirrel [3659]
Path:                  /Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel
Identifier:            im.rime.inputmethod.Squirrel
Version:               0.15.2
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Squirrel [3659]
User ID:               501

Date/Time:             2021-02-22 19:23:11.589 +0800
OS Version:            macOS 11.2.1 (20D74)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        E885E960-2011-FFAB-34B9-53956BC676D3


Time Awake Since Boot: 1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: Permission denied: "/Library/Input Methods/Squirrel.app/Contents/SharedSupport/build/squirrel.yaml"

安装了plum，有不少yaml，但是仍旧没有找到squirrel.yaml
