### ISSUE TITLE
BBGGRR color format creates unnecessary barriers for skin creators

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/squirrel#443]
https://github.com/rime/squirrel/blob/a2c0348c1a038f2a4cc963e1f818cbcda2fa997a/SquirrelConfig.m#L172
This order is different from most color pickers, design softwares and css color format, creating completely unnecessary conversion for skin customization.

**Comment by lotem** [comment]
It's a hexademical number, beginning from least significant byte, it reads in the order RGB.
But in order to support the A part and not forcing existing RGB colors to explictily add an extra `0xFF000000` alpha component, the YAML color is no longer read as interger but parsed into RGBA components from string.

My proposal is to support an extra CSS-style color selector like `#rrggbb`.

**Comment by LEOYoon-Tsaw** [comment]
There's still need a way to express transparency, [RGBA_color_model](https://en.wikipedia.org/wiki/RGBA_color_model) is a good option.
I suggest we define `#rrggbb` and `#rrggbbaa` both valid color codes.

**Comment by GJRobert** [comment]
Right now, you can use tools such as [Rime西米](https://bennyyip.github.io/Rime-See-Me/) or [Rime 西米 for Squirrel](https://gjrobert.github.io/Rime-See-Me-squirrel/), to help get BBGGRR directly from the color picker, and generate color theme codes for you.
