### ISSUE TITLE
Is there any way to set RIME as the default IME of my Mac?

### ISSUE THREAD

**Issue by zgw3kszo** [rime/squirrel#476]
My Mac doesn't recognise RIME as a _Latin based_ IME so it does not allow me to remove the other IME's I once used to input Latin characters. Currently I use the CapsLock function as built into RIME to switch between character input and Latin input so I have no need for other IME's to be on the list of input methods for my Mac. The system does not allow me to remove these unneeded IME's via System Preferences so I am wondering, is there anyway to set RIME to be the default input for my system? Along with that, is there any reliable way to remove the MacOS CapsLock delay in MacOS 11.1?

**Comment by lotem** [comment]
I guess macOS preferences ask for at least one *keyboard layout* added to the list.
That is reasonable because IME depends on the active keyboard layout to know which key produces which character.

I'm not sure if there is a way to remove the keyboard entry.
There were similar discussions in previous issues. If you find more information, please link to this thread.
