### ISSUE TITLE
INSTALL.md needs update

### ISSUE THREAD

**Issue by lotem** [rime/squirrel#480]
https://github.com/rime/squirrel/blob/master/INSTALL.md

update instructions to install tools, dependencies and to build librime:
https://github.com/rime/librime/blob/master/README-mac.md

add an option (and helper script) to get the latest librime release.

**Comment by yanhuacuo** [comment]
公子，现在的编译文档有问题。

从前的一直可用的编译环境，在编译新代码时，先是提示：

缺少 `kyoto-cabinet` 与 `pkg-config`

brew 安装了上述两个包之后，编译 librime 时提示

``````
CMake Error at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: locale) (found suitable version "1.75.0",
  minimum required is "1.46.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  plugins/librime-charcode/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/yan/Documents/squirrel-2021/librime/build/CMakeFiles/CMakeOutput.log".
``````

看来是 boost 的问题，不过，brew 已经装不上 1.60 版本的 boost 了：

```````
Error: boost@1.60 has been disabled because it is a versioned formula!
```````

因为需要 [librime-charcode](https://github.com/rime/librime-charcode) 插件，所以这个编译无法通过。

同时，[librime-legacy](https://github.com/rime/librime-legacy) 也无法编译通过。

希望公子指点。

**Comment by lotem** [comment]
插件可以引进新的依赖，`INSTALL.md`所介绍的步骤并没有添加特定插件，当然不能保证添加额外的插件后这些步骤可以不加改动而使构建成功。

文档已经更新完毕。结单。

**Comment by yanhuacuo** [comment]
> 插件可以引进新的依赖，`INSTALL.md`所介绍的步骤并没有添加特定插件，当然不能保证添加额外的插件后这些步骤可以不加改动而使构建成功。
> 
> 文档已经更新完毕。结单。

但是 [librime-charcode](https://github.com/rime/librime-charcode)  与 [librime-legacy](https://github.com/rime/librime-legacy) 被引入后，构建 librime 时，顺利通过`make xcode/thirdparty`后，无法执行 `make xcode` 的编译步骤（boost库花式报错，已尝试了文档里的所有建议），求 Mac 下的「plugins」编译指导  :(

**Comment by Dreamer57** [comment]
> > 插件可以引进新的依赖，`INSTALL.md`所介绍的步骤并没有添加特定插件，当然不能保证添加额外的插件后这些步骤可以不加改动而使构建成功。
> > 文档已经更新完毕。结单。
> 
> 但是 [librime-charcode](https://github.com/rime/librime-charcode) 与 [librime-legacy](https://github.com/rime/librime-legacy) 被引入后，构建 librime 时，顺利通过`make xcode/thirdparty`后，无法执行 `make xcode` 的编译步骤（boost库花式报错，已尝试了文档里的所有建议），求 Mac 下的「plugins」编译指导 :(

@yanhuacuo 大哥你的问题解决了吗？
